version: '3.9'

services:
  besu:
    image: ${BESU_REPO:-dcspark/besu}:${BESU_TAG:-22.10.0-milkomeda-c1}
    restart: "always"
    command:
      - --config-file=/config/config.toml
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=c1-evm-passive
      - LOG4J_CONFIGURATION_FILE=/config/log-config.xml
      - BESU_OPTS=-Xmx1G
    volumes:
      - ./config:/config
      - ${DATA_DIR:-./storage/data}:/opt/besu/data
      - ${LOGS_DIR:-./storage/logs}:/tmp/besu
    # network_mode: "host"
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
      - 8547:8547/tcp
      - 9545:9545/tcp
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
